# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    http_client:
        scoped_clients:
            photon.client:
                base_uri: '%env(PHOTON_URL)%'
                headers:
                    Accept: 'application/json'
                    User-Agent: 'geo-microservice/%env(APP_ENV)%'
            osrm.client:
                base_uri: '%env(OSRM_URL)%'
                headers:
                    Accept: 'application/json'
                    User-Agent: 'geo-microservice/%env(APP_ENV)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
